name: Manual

on:
  push:
    branches: [master]
    paths:
    - '*.1'
  pull_request:
    paths:
    - '*.1'

permissions:
  contents: read

jobs:
  man:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Dependency
      run: sudo apt-get install -y mandoc

    - name: Lint
      run: mandoc -W warning -T utf8 abduco.1 > /dev/null
